apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "webapp.fullname" . }}-vol-redis
  annotations:
    volume.beta.kubernetes.io/storage-class: basic
  {{- if .Values.cloneSource }}
    trident.netapp.io/cloneFromPVC: {{.Values.cloneSource}}-webapp-vol-redis
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ template "webapp.fullname" . }}-redis
  name: {{ template "webapp.fullname" . }}-redis
spec:
  ports:
    # the port that this service should serve on
    - port: 6379
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: {{ template "webapp.fullname" . }}-redis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ template "webapp.fullname" . }}-webapp
  name: {{ template "webapp.fullname" . }}-webapp
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      nodePort: {{.Values.service.nodePort}}
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: {{ template "webapp.fullname" . }}-webapp
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "webapp.fullname" . }}-redis
  labels:
    name: {{ template "webapp.fullname" . }}-redis
spec:
  containers:
    - resources:
        limits :
          cpu: 0.5
      image: {{.Values.redisImage.name}}:{{.Values.redisImage.tag}}
      command:
        - "redis-server"
      args:
        - "--appendonly" 
        - "yes"
      name: {{ template "webapp.fullname" . }}-redis
      ports:
        - containerPort: 6379
          name: redis
      volumeMounts:
          # name must match the volume name below
        - name: redis-persistent-storage
          # mount path within the container
          mountPath: /data
  volumes:
    - name: redis-persistent-storage
      persistentVolumeClaim:
        claimName: {{ template "webapp.fullname" . }}-vol-redis
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "webapp.fullname" . }}-webapp
  labels:
    name: {{ template "webapp.fullname" . }}-webapp
spec:
  containers:
    - image: {{.Values.webappImage.name}}:{{.Values.webappImage.tag}}
      name: {{ template "webapp.fullname" . }}-webapp
      env:
        - name: USE_REDIS_PORT
          value: "6379"
        - name: USE_REDIS_HOST
          value: {{ template "webapp.fullname" . }}-redis
      ports:
        - containerPort: 80
          name: webapp
